---
kind: pipeline
type: docker
name: compile-for-m68k

steps:
  - name: compile-m68k-000
    image: walkero/docker4amigavbcc:latest-m68k
    commands:
      - ls -la /drone
      - cd /opt/code/iGame
      - make -f Makefile.linux
    # volumes:
    #   - './code:/opt/code'


trigger:
  branch:
    include:
      - drone-CI
  event:
    include:
      - push
