---
kind: pipeline
type: docker
name: compile-iGame

steps:
- name: compile-m68k-000
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.linux
    - ls -la /drone/src
- name: compile-m68k-030
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.linux iGame.030
    - ls -la /drone/src
- name: compile-m68k-040
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.linux iGame.040
    - ls -la /drone/src
- name: compile-m68k-060
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.linux iGame.060
    - ls -la /drone/src
- name: compile-os4
  image: walkero/docker4amigavbcc:latest-ppc
  commands:
    - ls -la /drone/src
    - cd /drone/src
    - make -f Makefile.linux iGame.AOS4
    - ls -la /drone/src


trigger:
  branch:
    include:
      - drone-CI
  event:
    include:
      - push
