---
kind: pipeline
type: docker
name: compile-iGame

steps:
- name: compile-m68k-000
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.docker
- name: compile-m68k-030
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.docker iGame.030
- name: compile-m68k-040
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.docker iGame.040
- name: compile-m68k-060
  image: walkero/docker4amigavbcc:latest-m68k
  commands:
    - cd /drone/src
    - make -f Makefile.docker iGame.060
- name: compile-os4
  image: walkero/docker4amigavbcc:latest-ppc
  commands:
    - cd /drone/src
    - make -f Makefile.docker iGame.OS4


trigger:
  branch:
    include:
      - develop
  event:
    include:
      - push
